export const CAMPAIGN_PAUSE_UPDATE= "CAMPAIGN_PAUSE_UPDATE";
export const CAMPAIGN_DELETE = "CAMPAIGN_DELETE";
export const CAMPAIGN_RENAME = "CAMAPAIGN_RENAME";
export const ADD_COMMENT ='ADD_COMMENT';